-- MySQL Script generated by MySQL Workbench
-- Fri Jun 24 11:08:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DogGo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DogGo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DogGo` DEFAULT CHARACTER SET utf8 ;
USE `DogGo` ;

-- -----------------------------------------------------
-- Table `DogGo`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DogGo`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `doc_identificacion` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `primer_apellido` VARCHAR(45) NOT NULL,
  `segundo_apellido` VARCHAR(45) NULL,
  `email` VARCHAR(150) NOT NULL,
  `clave` VARCHAR(512) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  `foto` BLOB NULL,
  `metodo_pago_id` INT NOT NULL,
  PRIMARY KEY (`id`, `metodo_pago_id`),
  UNIQUE INDEX `dni_UNIQUE` (`doc_identificacion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DogGo`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DogGo`.`direccion` (
  `id` INT NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DogGo`.`direccion_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DogGo`.`direccion_has_usuario` (
  `direccion_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`direccion_id`, `usuario_id`),
  INDEX `fk_direccion_has_usuario_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_direccion_has_usuario_direccion_idx` (`direccion_id` ASC) VISIBLE,
  CONSTRAINT `fk_direccion_has_usuario_direccion`
    FOREIGN KEY (`direccion_id`)
    REFERENCES `DogGo`.`direccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direccion_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `DogGo`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DogGo`.`perros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DogGo`.`perros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `peso_kg` FLOAT NOT NULL,
  `edad` INT(2) NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `raza` VARCHAR(45) NOT NULL,
  `microchip` BIT NOT NULL,
  `esterilizado` BIT NOT NULL,
  `inf_adicional` VARCHAR(400) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DogGo`.`usuario_has_perro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DogGo`.`usuario_has_perro` (
  `usuario_id` INT NOT NULL,
  `perro_id` INT NOT NULL,
  `num_perros` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `perro_id`),
  INDEX `fk_usuario_has_perro_perro1_idx` (`perro_id` ASC) VISIBLE,
  INDEX `fk_usuario_has_perro_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_perro_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `DogGo`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_perro_perro1`
    FOREIGN KEY (`perro_id`)
    REFERENCES `DogGo`.`perros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DogGo`.`paseador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DogGo`.`paseador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `doc_identificacion` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `primer_apellido` VARCHAR(45) NOT NULL,
  `segundo_apellido` VARCHAR(45) NULL,
  `email` VARCHAR(150) NOT NULL,
  `clave` VARCHAR(18) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `disponibilidad` VARCHAR(200) NOT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  `max_cant_perros` INT NOT NULL,
  `peso_perro` VARCHAR(45) NOT NULL,
  `esterilizado` BIT NOT NULL,
  `reseñas` VARCHAR(400) NULL,
  `valoracion` FLOAT NULL,
  `precio_paseo` FLOAT NOT NULL,
  `foto_perfil` BLOB NULL,
  `galeria` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DogGo`.`paseador_has_direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DogGo`.`paseador_has_direccion` (
  `paseador_id` INT NOT NULL,
  `direccion_id` INT NOT NULL,
  PRIMARY KEY (`paseador_id`, `direccion_id`),
  INDEX `fk_paseador_has_direccion_direccion1_idx` (`direccion_id` ASC) VISIBLE,
  INDEX `fk_paseador_has_direccion_paseador1_idx` (`paseador_id` ASC) VISIBLE,
  CONSTRAINT `fk_paseador_has_direccion_paseador1`
    FOREIGN KEY (`paseador_id`)
    REFERENCES `DogGo`.`paseador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paseador_has_direccion_direccion1`
    FOREIGN KEY (`direccion_id`)
    REFERENCES `DogGo`.`direccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DogGo`.`hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DogGo`.`hotel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `piscina` BIT NOT NULL,
  `valoracion` FLOAT NULL,
  `precio_noche` FLOAT NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DogGo`.`hotel_has_direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DogGo`.`hotel_has_direccion` (
  `hotel_id` INT NOT NULL,
  `direccion_id` INT NOT NULL,
  PRIMARY KEY (`hotel_id`, `direccion_id`),
  INDEX `fk_hotel_has_direccion_direccion1_idx` (`direccion_id` ASC) VISIBLE,
  INDEX `fk_hotel_has_direccion_hotel1_idx` (`hotel_id` ASC) VISIBLE,
  CONSTRAINT `fk_hotel_has_direccion_hotel1`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `DogGo`.`hotel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hotel_has_direccion_direccion1`
    FOREIGN KEY (`direccion_id`)
    REFERENCES `DogGo`.`direccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DogGo`.`tipo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DogGo`.`tipo_pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DogGo`.`guarderia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DogGo`.`guarderia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio_noche` FLOAT NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `valoracion` FLOAT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DogGo`.`restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DogGo`.`restaurante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `valoracion` FLOAT NULL,
  `email` VARCHAR(150) NOT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DogGo`.`catalogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DogGo`.`catalogo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `guarderia_id` INT NOT NULL,
  `hotel_id` INT NOT NULL,
  `paseador_id` INT NOT NULL,
  `restaurante_id` INT NOT NULL,
  `tipo_servicio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `guarderia_id`, `hotel_id`, `paseador_id`, `restaurante_id`),
  INDEX `fk_catalogo_guarderia1_idx` (`guarderia_id` ASC) VISIBLE,
  INDEX `fk_catalogo_hotel1_idx` (`hotel_id` ASC) VISIBLE,
  INDEX `fk_catalogo_paseador1_idx` (`paseador_id` ASC) VISIBLE,
  INDEX `fk_catalogo_restaurante1_idx` (`restaurante_id` ASC) VISIBLE,
  CONSTRAINT `fk_catalogo_guarderia1`
    FOREIGN KEY (`guarderia_id`)
    REFERENCES `DogGo`.`guarderia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_catalogo_hotel1`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `DogGo`.`hotel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_catalogo_paseador1`
    FOREIGN KEY (`paseador_id`)
    REFERENCES `DogGo`.`paseador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_catalogo_restaurante1`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `DogGo`.`restaurante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DogGo`.`servicio_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DogGo`.`servicio_usuario` (
  `id` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  `catalogo_id` INT NOT NULL,
  `perros_id` INT NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `estado_reserva` VARCHAR(100) NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `nombre_servicio` VARCHAR(45) NOT NULL,
  `fecha_inicio_reserva` DATE NULL,
  `fecha_final_reservado` DATE NULL,
  PRIMARY KEY (`id`, `usuario_id`, `catalogo_id`, `perros_id`),
  INDEX `fk_usuario_has_catalogo_catalogo1_idx` (`catalogo_id` ASC) VISIBLE,
  INDEX `fk_usuario_has_catalogo_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_servicio_usuario_perros1_idx` (`perros_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_catalogo_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `DogGo`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_catalogo_catalogo1`
    FOREIGN KEY (`catalogo_id`)
    REFERENCES `DogGo`.`catalogo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_usuario_perros1`
    FOREIGN KEY (`perros_id`)
    REFERENCES `DogGo`.`perros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DogGo`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DogGo`.`factura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_creacion` DATETIME NOT NULL,
  `total_a_pagar` FLOAT NOT NULL,
  `servicio_usuario_id` VARCHAR(45) NOT NULL,
  `tipo_pago_id` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `servicio_usuario_id`, `tipo_pago_id`),
  INDEX `fk_factura_servicio_usuario1_idx` (`servicio_usuario_id` ASC) VISIBLE,
  INDEX `fk_factura_tipo_pago1_idx` (`tipo_pago_id` ASC) VISIBLE,
  CONSTRAINT `fk_factura_servicio_usuario1`
    FOREIGN KEY (`servicio_usuario_id`)
    REFERENCES `DogGo`.`servicio_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_tipo_pago1`
    FOREIGN KEY (`tipo_pago_id`)
    REFERENCES `DogGo`.`tipo_pago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DogGo`.`guarderia_has_direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DogGo`.`guarderia_has_direccion` (
  `guarderia_id` INT NOT NULL,
  `direccion_id` INT NOT NULL,
  PRIMARY KEY (`guarderia_id`, `direccion_id`),
  INDEX `fk_guarderia_has_direccion_direccion1_idx` (`direccion_id` ASC) VISIBLE,
  INDEX `fk_guarderia_has_direccion_guarderia1_idx` (`guarderia_id` ASC) VISIBLE,
  CONSTRAINT `fk_guarderia_has_direccion_guarderia1`
    FOREIGN KEY (`guarderia_id`)
    REFERENCES `DogGo`.`guarderia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_guarderia_has_direccion_direccion1`
    FOREIGN KEY (`direccion_id`)
    REFERENCES `DogGo`.`direccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DogGo`.`restaurante_has_direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DogGo`.`restaurante_has_direccion` (
  `restaurante_id` INT NOT NULL,
  `direccion_id` INT NOT NULL,
  PRIMARY KEY (`restaurante_id`, `direccion_id`),
  INDEX `fk_restaurante_has_direccion_direccion1_idx` (`direccion_id` ASC) VISIBLE,
  INDEX `fk_restaurante_has_direccion_restaurante1_idx` (`restaurante_id` ASC) VISIBLE,
  CONSTRAINT `fk_restaurante_has_direccion_restaurante1`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `DogGo`.`restaurante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restaurante_has_direccion_direccion1`
    FOREIGN KEY (`direccion_id`)
    REFERENCES `DogGo`.`direccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
